spring.application.name=Driving_License_Management_System-backend

jdbc:mysql://localhost:3306/dlms_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTCspring.datasource.username=root
spring.datasource.password=123454321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
